ExternalConfigs:
    - configs/handset
    - configs/tablet

Default:
    Active: True
    Baseline: kickstarts
    Language: en_US.UTF-8
    Keyboard: us
    SaveRepos: True
    Timezone: America/Los_Angeles
    RootPass: meego
    DefaultUser: meego
    DefaultUserPass: meego
    PartSize: 1900
    Schedule: "*"
    Active: True
    Mic2Options: -f raw --save-kernel --arch=armv7nhl --record-pkgs=name
    Architecture: armv7nhl
    Desktop: DUI
    Session: "/usr/bin/mcompositor"
    StartX: True
    Kernel: kernel-adaptation-n900
    Groups:
        - MeeGo Compliance
        - MeeGo Core
        - MeeGo Base Development
        - Minimal MeeGo X Window System
        - Nokia N900 Support
        - Nokia N900 Proprietary Support
    ExtraPackages:
        - xorg-x11-utils-xev
        # Add theme for N900 DE
        - meegotouch-theme-n900de
        # IM application
        - peregrine-plain-qml
        # Add splash screen stuff
        - generic-backgrounds
        - plymouth-lite
        # Adding widgetsgallery
        - meegotouch-demos
        # Install mce to enable screen blanking
        - mce
        # Make sure we have meego-ux-components in the images for developers
        - meego-ux-components
        # Install mad-developer for SDK usage
        - mad-developer
    RemovePackages:
        # No need to install phonesim on N900 we have real modem.
        - phonesim
        # Removing corewatcher because that is consuming way too much disk
        # space currently with unstable apps.
        - corewatcher
        # Style causing a lot of crashes so removing for now.
        # https://bugs.meego.com/show_bug.cgi?id=16894
        - meegotouch-qt-style
    PostScripts:
        - cleanup
        - nocursor
        - serial-n900
        - rpm
        - meegotouch-n900
        - bootchart
        - fstab-n900
        - arch-armv7nhl
        - handset-app-theme-fixes
        - plymouth-lite-n900
        - meegotouch-translations
        - prelink
    NoChrootScripts:
        - buildname
    Repos:
        - oss-1.2-daily
        - non-oss-1.2-daily

N900DEHANDSET:
    Part: n900-de
    Groups:
        - X for Handsets
        - MeeGo Handset Desktop
        - MeeGo Handset Applications
    ExtraPackages:
        # Add separate volume app so we have at least some volume control in the images.
        - meegovolume

N900DETABLET:
    Part: n900-de
    Groups:
        - MeeGo Tablet
        - MeeGo Tablet Applications
    ExtraPackages:
        # These apps are not in Tablet so we add them from handset
        - meego-handset-dialer
        - meego-handset-sms
        # Added to enable camera backend
        - gst-plugins-camera
        # Install fennec-qt because meego-app-browser doesn't compile for arm.
        - fennec-qt
    RemovePackages:
        # meego-app-browser doesn't compile for ARM currently so we can't install it.
        - meego-app-browser
        - meego-app-browser-ffmpeg-oss
    PostScripts:
        - n900-tablet-gconf
        - tablet-sensor-hack
        - meego-ux-daemon-n900-homekey
