ExternalConfigs:
    - configs/handset
    - configs/tablet

Default:
    Active: True
    Baseline: kickstarts
    Language: en_US.UTF-8
    Keyboard: us
    SaveRepos: True
    Timezone: America/Los_Angeles
    RootPass: meego
    DefaultUser: meego
    DefaultUserPass: meego
    PartSize: 1900
    Schedule: "*"
    Active: True

N900DE:
    Part: n900-de
    BootloaderTimeout: 
    BootloaderAppend: 
    StartX: True
    Groups:
        - MeeGo Compliance
        - MeeGo Core
        - MeeGo Base Development
        - Minimal MeeGo X Window System
        - Nokia N900 Support
        - Nokia N900 Proprietary Support
    ExtraPackages:
        - xorg-x11-utils-xev
    Kernel: kernel-adaptation-n900
    PostScripts:
        - cleanup
        - nocursor
        - serial-n900
        - rpm
        - meegotouch-n900
        - bootchart
        - fstab-n900
        - arch-armv7nhl
    NoChrootScripts:
        - buildname
    Architecture: armv7nhl
    Desktop: DUI
    Session: "/usr/bin/mcompositor"
    Mic2Options: -f raw --save-kernel --arch=armv7nhl --record-pkgs=name  --outdir=images


