ExternalConfigs:
    - configs/1.2/handset
    - configs/1.2/tablet
    - configs/1.3/handset

Default:
    Active: True
    Language: en_US.UTF-8
    Keyboard: us
    SaveRepos: True
    Timezone: America/Los_Angeles
    RootPass: meego
    DefaultUser: meego
    DefaultUserPass: meego
    PartSize: 1900
    Schedule: "*"
    Active: True
    PostScripts:
        - cleanup
        - nocursor
        - rpm
        - bootchart
        - handset-app-theme-fixes
        - plymouth-lite-ce
        - meegotouch-translations
        - prelink
    NoChrootScripts:
        - buildname

CE-HANDSET-1.3:
    Baseline: "1.3"
    Repos:
        - oss-trunk-testing-daily
        - mtf-trunk-testing
        - ce-1.3-testing
    Groups:
        - Compliance
        - Core
        - Base Development
        - Common User Interface
        - MTF Handset UX
        - Community Edition Base
    ExtraPackages:
        # Until https://meego.gitorious.org/meego-os-base/package-groups/merge_requests/47
        # is merged to the package groups.
        - basesystem
    PostScripts:
        - uxlaunch-symlink-mtf
        # Disable corewatcher on boot
        - systemd-corewatcher-disable

CEHANDSET:
    Baseline: "1.2"
    Desktop: DUI
    Session: "/usr/bin/mcompositor"
    StartX: True
    Groups:
        - MeeGo Compliance
        - MeeGo Core
        - MeeGo Base Development
        - Minimal MeeGo X Window System
        - X for Handsets
        - MeeGo Handset Desktop
        - MeeGo Handset Applications
        # Adding the MeeGo UX applications.
        - MeeGo Tablet Applications
    ExtraPackages:
        - xorg-x11-utils-xev
        # Add theme for N900 DE
        - meegotouch-theme-n900de
        # Add splash screen images
        - ce-backgrounds
        # Splash screen are shown with this
        - plymouth-lite
        # Adding widgetsgallery
        - meegotouch-demos
        # Install mce to enable screen blanking
        - mce
        # Install mad-developer for SDK usage
        - mad-developer
        # Qt Webkit is missing from the images
        - libqtwebkit4 
        - libqtwebkit-qmlwebkitplugin
        # Add resource policy client for debugging resource rules
        - libresource-client
        ### pyside ###
        - python-qtmobility
        - shiboken
        ### Community apps ###
        # IM application
        - peregrine-plain-qml
        # Cat related game
        - info.vivainio.qatbowling
        # Reddit reader
        - info.vivainio.qmlreddit
        # Facebook client
        - com.substanceofcode.kasvopus
        # Helium Mobile Browser
        - mobilebrowser
        # QML Based package manager
        - mg-package-manager
        # Include new terminal
        - meego-terminal
        # Adding iotop for testing purposes
        - iotop
        # Add text based browser
        - lynx
        # Add contact import package for retrieval of Maemo contacts.
        - maemo-contacts-import
        # IRC client
        - f-irc
        # Qt based game
        - qtflyingbus
        # Qt/QML components and models
        - qt-components
        - qt-components-base-icons
        # Add meego-pinquery package to add support for SIM cards with PIN code.
        - meego-pinquery
        # Adding usb-moded to the images, this will give us possibility to
        # choose between PC Suite mode and Mass storage mode.
        - usb-moded
        # replacement for meegocamera
        - meego-handset-camera
        # Control panel applet to control usb-moded
        - meegotouchcp-usb
        # Control panel applet for gprs
        - meegotouchcp-gprs
        # Control panel applet for profiles
        - meegotouchcp-profiles
        # Control panel applet for cellular
        - meegotouchcp-cellular
        # We need this so we can select between silent and general profiles
        - profiled
        # Because of following bugs we need to install the package manually:
        # https://bugs.meego.com/show_bug.cgi?id=19010
        # https://bugs.meego.com/show_bug.cgi?id=19011
        # https://bugs.meego.com/show_bug.cgi?id=19013
        - meego-ux-sharing-qml-ui
        # Orientation with MeeGo UX apps do not work without this
        - orientation-contextkit-sensor
        # Workaround for https://bugs.meego.com/show_bug.cgi?id=16394
        # Copy the .desktop files from this to the right places as temp solution.
        - meego-ux-appgrid
        # MeeGo community Apps client
        - appsclient-handset
        # Make sure we have meego-ux-components in the images for developers
        - meego-ux-components
    RemovePackages:
        # Removing corewatcher because that is consuming way too much disk
        # space currently with unstable apps.
        - corewatcher
        # No need to install phonesim on N900 we have real modem.
        - phonesim
        # Style causing a lot of crashes so removing for now.
        # https://bugs.meego.com/show_bug.cgi?id=16894
        - meegotouch-qt-style
        # Save some more memory by removing applifed as well.
        - meegotouch-applifed
        # Sreadahead only slows us down as we don't have any spinning platters
        - sreadahead
        # Remove nokia-usb-networking because it conflicts with usb-moded
        - nokia-usb-networking
        # Remove meegocamera replaced by meego-handset-camera
        - meegocamera
        # Removing social web as we are not using it.
        - meegotouchcp-socialweb 
        - meego-handset-socialweb
        # Remove unworking handset chat application
        - meego-handset-chat 
        - meegotouchcp-chat
        # Save some more memory by removing the applauncherd
        - meegotouch-applauncherd
        # Just to make sure we don't have problems with 
        # https://bugs.meego.com/show_bug.cgi?id=17695
        - meego-handset-icon-theme
    PostScripts:
        - disable-unused-daemons
        # We in order to get MeeGo UX apps launch properly we need this
        - meego-ux-ce-gconf
        # Disabled for now because of https://bugs.meego.com/show_bug.cgi?id=18759
        #- create-tracker-cache
        # Rest of the workaround for dependencies of https://bugs.meego.com/show_bug.cgi?id=16394
        - meego-ux-desktop-file-fix
        # Lets delay some of the apps after the home so the home screen 
        # is available earlier.
        - meegotouch-home-delay-app-startup

CETABLET:
    Baseline: "1.2"
    Desktop: DUI
    Session: "/usr/bin/mcompositor"
    StartX: True
    Groups:
        - MeeGo Compliance
        - MeeGo Core
        - MeeGo Base Development
        - Minimal MeeGo X Window System
        - MeeGo Tablet
        - MeeGo Tablet Applications
    ExtraPackages:
        - xorg-x11-utils-xev
        # Add theme for N900 DE
        - meegotouch-theme-n900de
        # Add splash screen images
        - ce-backgrounds
        # Splash screen are shown with this
        - plymouth-lite
        # Adding widgetsgallery
        - meegotouch-demos
        # Install mce to enable screen blanking
        - mce
        # Install mad-developer for SDK usage
        - mad-developer
        # Qt Webkit is missing from the images
        - libqtwebkit4 
        - libqtwebkit-qmlwebkitplugin
        # Add resource policy client for debugging resource rules
        - libresource-client
        ### pyside ###
        - python-qtmobility
        - shiboken
        ### Community apps ###
        # IM application
        - peregrine-plain-qml
        # Cat related game
        - info.vivainio.qatbowling
        # Reddit reader
        - info.vivainio.qmlreddit
        # Facebook client
        - com.substanceofcode.kasvopus
        # Helium Mobile Browser
        - mobilebrowser
        # QML Based package manager
        - mg-package-manager
        # Include new terminal
        - meego-terminal
        # Adding iotop for testing purposes
        - iotop
        # Add text based browser
        - lynx
        # Add contact import package for retrieval of Maemo contacts.
        - maemo-contacts-import
        # IRC client
        - f-irc
        # Qt based game
        - qtflyingbus
        # Qt/QML components and models
        - qt-components
        - qt-components-base-icons
        # These apps are not in Tablet so we add them from handset
        - meego-handset-dialer
        - meego-handset-sms
        # Install fennec-qt because meego-app-browser doesn't work properly.
        - fennec-qt
        # Make sure we have meego-ux-components in the images for developers
        - meego-ux-components
    RemovePackages:
        # Removing corewatcher because that is consuming way too much disk
        # space currently with unstable apps.
        - corewatcher
        # No need to install phonesim on N900 we have real modem.
        - phonesim
        # Style causing a lot of crashes so removing for now.
        # https://bugs.meego.com/show_bug.cgi?id=16894
        - meegotouch-qt-style
        # Save some more memory by removing applifed as well.
        - meegotouch-applifed
        # Sreadahead only slows us down as we don't have any spinning platters
        - sreadahead
        # Workaround for https://bugs.meego.com/show_bug.cgi?id=18662
        - pulseaudio-modules-tablet-common
        - pulseaudio-modules-tablet-mainvolume
        # Workaround for https://bugs.meego.com/show_bug.cgi?id=18667
        - policy-settings-tablet
        # Just to make sure we don't have problems with 
        # https://bugs.meego.com/show_bug.cgi?id=17695
        - meego-handset-icon-theme
    PostScripts:
        - disable-unused-daemons
        # Disabled for now because of https://bugs.meego.com/show_bug.cgi?id=18759
        #- create-tracker-cache
        # We in order to get MeeGo UX apps launch properly we need this
        - meego-ux-ce-gconf
