Default:
    Active: True
    Language: en_US.UTF-8
    Keyboard: us
    SaveRepos: True
    Timezone: America/Los_Angeles
    RootPass: meego
    DefaultUser: meego
    DefaultUserPass: meego
    PartSize: 1900

N900DE:
    Part: n900-de
    BootloaderTimeout: 
    BootloaderAppend: 
    StartX: True
    Groups:
        - MeeGo Compliance
        - MeeGo Core
        - MeeGo Base Development
        - Minimal MeeGo X Window System
        - Nokia N900 Support
        - Nokia N900 Proprietary Support
    ExtraPackages:
        - xorg-x11-utils-xev
    Kernel: kernel-adaptation-n900
    PostScripts:
        - cleanup
        - nocursor
        - serial-n900
        - rpm
        - meegotouch-n900
        - bootchart
        - fstab-n900
        - arch-armv7nhl
    NoChrootScripts:
        - buildname
    Architecture: armv7nhl
    Desktop: DUI
    Session: "/usr/bin/mcompositor"
    Mic2Options: -f raw --save-kernel --arch=armv7nhl --record-pkgs=name  --outdir=images

Configurations:
    -   Name: MeeGo Handset N900 Developer Edition (Sanity)
        Schedule: "*"
        Active: True
        Baseline: "handset"
        Platform: N900DE
        FileName: handset-armv7nhl-n900-de-sanity
        Groups:
            - X for Handsets 
            - MeeGo Handset Desktop
            - MeeGo Handset Applications
        Repos:
            - oss
            - non-oss
            - de-trunk
    -   Name: MeeGo Handset N900 Developer Edition (Acceptance)
        Schedule: "*"
        Active: True
        Baseline: "handset"
        Platform: N900DE
        FileName: handset-armv7nhl-n900-de-acceptance
        Groups:
            - X for Handsets 
            - MeeGo Handset Desktop
            - MeeGo Handset Applications
        Repos:
            - oss
            - non-oss
            - de-testing
    -   Name: MeeGo Tablet N900
        Schedule: "*"
        Active: True
        Baseline: "tablet"
        Platform: N900DE
        FileName: tablet-armv7nhl-n900
        Groups:
            - MeeGo Tablet
            - MeeGo Tablet Applications
        PostScripts:
            - n900-tablet-gconf
            - tablet-sensor-hack
        Repos:
            - oss-testing-live
            - non-oss-testing-live
            - de-testing
            - de-tablet-devel
        ExtraPackages:
            - meego-handset-dialer
            - meego-handset-sms
            - "-qmf"
            - "-acpid"
            - "-meego-app-browser"
            - "-meego-app-browser-ffmpeg-oss"

