ExternalConfigs:
    - configs/Mer/handset/

Default:
    Active: True
    Language: en_US.UTF-8
    Keyboard: us
    SaveRepos: True
    Timezone: America/Los_Angeles
    RootPass: meego
    DefaultUser: meego
    DefaultUserPass: meego
    PartSize: 1900
    Schedule: "*"
    Active: True
    PostScripts:
        - cleanup
        - nocursor
        - rpm
        - bootchart
        - handset-app-theme-fixes
        - plymouth-lite-ce
        - meegotouch-translations
        - prelink
    NoChrootScripts:
        - buildname

MER-CE-HANDSET:
    Baseline: "Mer"
    Groups:
        - MTF Handset UX
        - Community Edition Base
        - Community Edition Libraries
    ExtraPackages:
        # Until https://meego.gitorious.org/meego-os-base/package-groups/merge_requests/47
        # is merged to the package groups.
        - basesystem
    RemovePackages:
        - syncevolution
        - mce
        - dsme
        - meegotouch-inputmethodbridges
        - meegotouchcp-about
        - meegotouchcp-battery
        - meegotouchcp-display
        - meegotouchcp-gprs
        - meegotouchcp-offline
        - meegotouchcp-reset
        - meegotouchcp-theme
        - meegotouchcp-usb
        - meegotouchcp-wallpaper
        - meegotouchcp-warranty
        - xorg-x11-utils-xev
        - mad-developer
        - peregrine-plain-qml
        - org.pycage.musicshelf
        - fennec-qt
        - meego-handset-dialer
        - meego-handset-sms
        - meego-handset-people
        - meego-handset-video
        - meego-handset-photos
        - libdeclarative-messaging
        - libdeclarative-organizer
        - libqtsparql-tracker-direct
        - meego-handset-camera
        - appsclient-handset
    PostScripts:
        - uxlaunch-symlink-mtf
        # ohmd spam fix.
        - ohm-modules-ban
