Repositories:
    -   Name: mer-base-i586
        Url:  http://repo.pub.meego.com//Mer:/Trunk:/Base/standard/

    -   Name: mer-adaptation-x86
        Url:  http://repo.pub.meego.com/home:/sage:/Mer:/adaptation:/x86/Mer_i586/

    -   Name: mer-utils-i586
        Url:  http://repo.pub.meego.com//home:/sage:/Mer:/Utils/Mer_i586/

    -   Name: mer-mw-shared-i586
        Url:  http://repo.pub.meego.com/home:/sage:/Mer:/MW:/Shared/Mer_i586/

    -   Name: mer-ux-mtf-i586
        Url:  http://repo.pub.meego.com//Project:/MTF/Mer_i586/

    -   Name: mer-ce-apps-i586
        Url:  http://repo.pub.meego.com//Project:/DE:/Trunk:/Testing:/1.3/Mer_i586/

