# -*-mic2-options-*- -f livecd --arch=i586 --record-pkgs=name --pkgmgr=yum -*-mic2-options-*-

# 
# Do not Edit! Generated by:
# kickstarter.py
# 

lang en_US.UTF-8
keyboard us
timezone --utc America/Los_Angeles
part / --size 3000 --ondisk sda --fstype=ext3
rootpw meego 
xconfig --startxonboot
bootloader  --timeout=0   --menu="autoinst:Installation:systemd.unit=installer-shell.service"

user --name meego  --groups audio,video --password meego 

repo --name=mer-base-i586 --baseurl=http://repo.pub.meego.com//Mer:/Trunk:/Base/standard/ --save --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego
repo --name=mer-adaptation-x86 --baseurl=http://repo.pub.meego.com/home:/sage:/Mer:/adaptation:/x86/Mer_i586/ --save --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego
repo --name=mer-utils-i586 --baseurl=http://repo.pub.meego.com//home:/sage:/Mer:/Utils/Mer_i586/ --save --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego
repo --name=mer-mw-shared-i586 --baseurl=http://repo.pub.meego.com/home:/sage:/Mer:/MW:/Shared/Mer_i586/ --save --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego
repo --name=mer-ux-mtf-i586 --baseurl=http://repo.pub.meego.com//Project:/MTF/Mer_i586/ --save --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego
repo --name=mer-ce-apps-i586 --baseurl=http://repo.pub.meego.com//Project:/DE:/Trunk:/Testing:/1.3/Mer_i586/ --save --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego

%packages

@MTF Handset UX
@Community Edition Base
@Community Edition Libraries

kernel-adaptation-pc

basesystem
acpid
linux-firmware
installer-shell
xorg-x11-drv-mtev
xorg-x11-drv-synaptics
xorg-x11-drv-intel
mesa-dri-i915-driver
mesa-dri-i965-driver
mesa-libGLESv2
contextkit-meego-battery-upower
zypper
openssh-clients
bash
boardname
coreutils
crda
deltarpm
e2fsprogs
file
filesystem
iproute
iputils
kbd
lsb-release
mailcap
meego-release
net-tools
nss
pam
passwd
prelink
procps
readline
rootfiles
rpm
setup
shadow-utils
shared-mime-info
systemd-sysv
time
udev
usbutils
util-linux
wireless-tools
wpa_supplicant
xdg-user-dirs
cjkuni-fonts
droid-sans-fonts
droid-sans-mono-fonts
droid-serif-fonts
fontpackages-filesystem
liberation-fonts-common
liberation-mono-fonts
liberation-sans-fonts
liberation-serif-fonts
uxlaunch
gzip
xorg-x11-server-Xorg
xorg-x11-drv-fbdev
xorg-x11-xauth
qt-qmlviewer
-syncevolution
-mce
-dsme
-meegotouch-inputmethodbridges
-meegotouchcp-about
-meegotouchcp-battery
-meegotouchcp-display
-meegotouchcp-gprs
-meegotouchcp-offline
-meegotouchcp-reset
-meegotouchcp-theme
-meegotouchcp-usb
-meegotouchcp-wallpaper
-meegotouchcp-warranty
-xorg-x11-utils-xev
-mad-developer
-peregrine-plain-qml
-org.pycage.musicshelf
-fennec-qt
-meego-handset-dialer
-meego-handset-sms
-meego-handset-people
-meego-handset-video
-meego-handset-photos
-libdeclarative-messaging
-libdeclarative-organizer
-libqtsparql-tracker-direct
-meego-handset-camera
-appsclient-handset
%end

%post

# save a little bit of space at least...
rm -f /boot/initrd*

# make sure there aren't core files lying around
rm -f /core*

# Remove cursor from showing during startup BMC#14991
echo "xopts=-nocursor" >> /etc/sysconfig/uxlaunch

# work around for poor key import UI in PackageKit
rm -f /var/lib/rpm/__db*
rpm --rebuilddb

# Normal bootchart is only 30 long so we use this to get longer bootchart during startup when needed.
cat > /sbin/bootchartd-long << EOF
#!/bin/sh
exec /sbin/bootchartd -n 4000
EOF
chmod +x /sbin/bootchartd-long

# Fix for https://bugs.meego.com/show_bug.cgi?id=15963
mkdir -p /usr/share/themes/base/meegotouch/
cp -rf /usr/share/themes/meego/meegotouch/dialer /usr/share/themes/base/meegotouch/

# Also some other apps need fixes for other themes than meego
cp -rf /usr/share/themes/meego/meegotouch/meegophotos /usr/share/themes/base/meegotouch/
cp -rf /usr/share/themes/meego/meegotouch/meegomusic /usr/share/themes/base/meegotouch/
cp -rf /usr/share/themes/meego/meegotouch/meegovideo /usr/share/themes/base/meegotouch/
# Hack to fix the plymouth based splash screen on N900
mv /usr/bin/ply-image /usr/bin/ply-image-real
cat > /usr/bin/ply-image << EOF
#!/bin/sh
echo 32 > /sys/class/graphics/fb0/bits_per_pixel
exec /usr/bin/ply-image-real $@
EOF
chmod +x /usr/bin/ply-image
# Remove some unwanted "engineering english" translations.
rm -f /usr/share/l10n/meegotouch/recovery*
# We can run the prelink only with qemu version 0.14 and newer.
qemu-arm-static -version | grep "0\.14"

if [ "x$?" == "x0" ]; then
    echo "QEMU version 0.14 running prelink."
    # Prelink can reduce boot time
    if [ -x /usr/sbin/prelink ]; then
        /usr/sbin/prelink -aRqm
    fi
else
    echo "QEMU version is not 0.14 so not running prelink."
fi


# Create a session file for MTF.
cat > /usr/share/xsessions/X-MEEGO-HS.desktop << EOF
[Desktop Entry]
Version=1.0
Name=mtf compositor session
Exec=/usr/bin/mcompositor
Type=Application
EOF

# Set symlink pointing to .desktop file 
ln -sf X-MEEGO-HS.desktop /usr/share/xsessions/default.desktop
# ohm outputs "No protocol specified" message couple of times a second, because of videoep module.
# See: https://bugs.meego.com/show_bug.cgi?id=22887
sed -i 's!ModulesBanned=!ModulesBanned=videoep!g' /etc/ohm/modules.ini

%end

%post --nochroot
if [ -n "$IMG_NAME" ]; then
    echo "BUILD: $IMG_NAME" >> $INSTALL_ROOT/etc/meego-release
fi


%end
