Name: Nemo Handset Pandaboard
FileName: handset-armv7l-pandaboard
Architecture: armv7l
Inherit:
    - MER
    - NEMO-HANDSET
    - NEMO-ADAPTATION-PANDABOARD
PostScripts:
    - meegotouch-mouse-ptr
    - pandaboard-sw-cursor-enable
    - qt-graphicssystem-opengl
