Name: Mer Handset N900 Community Edition (Testing)
Platform: NEMO-HANDSET
FileName: handset-armv7nhl-n900-ce-testing
Part: n900-ce
Mic2Options: -f raw --save-kernel --arch=armv7hl --record-pkgs=name --pkgmgr=yum
Architecture: armv7hl
Kernel: kernel-adaptation-n900
Repos:
    - mer-core-armv7hl
    - ce-adaptation-n9xx-common
    - ce-adaptation-n900
    - ce-utils-armv7hl
    - ce-mw-shared-armv7hl
    - ce-ux-mtf-armv7hl
    - ce-apps-armv7hl
Groups:
    - Nokia N900 Support
    - Nokia N900 Proprietary Support
ExtraPackages:
    # Non-oss part of N900 camera for focus etc.
    #- gst-nokia-camera
    # Adding n900 specific perf
    # TODO: Disabled atm. because of gcc 4.6.0 compile problems.
    #- perf-adaptation-n900
    # CE related n900 specific config so isn't in Nokia N900 Support.
    #- usb-moded-config-n900
    # Because of the SGX drivers we need setuid version of Xorg
    #- xorg-x11-server-Xorg-setuid
    # Battery management as upower doesn't work properly with 1.3 and N900
    #- contextkit-maemo-battery-rx51-bin
    - bme-rx-51-bin
    - dsme
    - gst-omapfb
    - openssh-server
    - openssh-clients
    - xterm
RemovePackages:
    # Conflicts with maemo battery.
    #- contextkit-meego-battery-upower
PostScripts:
    # TODO: Because of https://bugs.meego.com/show_bug.cgi?id=20493#c1
    # we can't use the armv7nhl here
    - arch-armv7hl
    - fstab-n900
    - meegotouch-n900
    # bq module causes instability, so removing for now.
    - n900-bq27x00_battery-removal
    # We don't have so much power with N900 than others so we need to wait a bit longer
    - mcompositor-app-wait-delay
