Name: Mer Handset IA32 Community Edition (Testing)
Platform: NEMO-HANDSET
FileName: handset-ia32-ce-testing
PartSize: 3000
FileSystem: ext3
Bootloader: True
#BootloaderAppend: "quiet"
BootloaderTimeout: 0
BootloaderOptions: --menu="autoinst:Installation:systemd.unit=installer-shell.service"
StartX: True
Architecture: ia32
Mic2Options: -f livecd --arch=i586 --record-pkgs=name --pkgmgr=yum
Kernel: kernel-adaptation-pc
Repos:
    - mer-core-i586
    - ce-adaptation-x86-generic
    - ce-utils-i586
    - ce-mw-shared-i586
    - ce-ux-mtf-i586
    - ce-apps-i586
Groups:
    - Intel x86 Generic Support