Name: Nemo Handset N900 (Testing)
FileName: handset-armv7hl-n900-testing
Architecture: armv7hl
Inherit:
    - MER
    - NEMO-HANDSET
    - NEMO-ADAPTATION-N900
ExtraPackages:
    # Wifi indicator needs this.
    - contextkit-maemo-mce
    # Adding n900 specific perf
    # TODO: Disabled atm. because of gcc 4.6.0 compile problems.
    #- perf-adaptation-n900
    # CE related n900 specific config so isn't in Nokia N900 Support.
    - usb-moded-config-n900
    - policy-settings-basic-n900
    - mce
    - meego-handset-camera
    - xorg-x11-xauth
PostScripts:
    # TODO: Because of https://bugs.meego.com/show_bug.cgi?id=20493#c1
    # we can't use the armv7nhl here
    - arch-armv7hl
    - meegotouch-n900
    # We don't have so much power with N900 than others so we need to wait a bit longer
    - mcompositor-app-wait-delay
