Name: Nemo Handset N950 (Testing)
Platform: NEMO-HANDSET
FileName: handset-armv7hl-n950-testing
PartSize: 3500
FileSystem: ext3
Mic2Options: -f fs --compress-disk-image=tar.bz2 --save-kernel --arch=armv7hl --record-pkgs=name --pkgmgr=yum
Architecture: armv7hl
Kernel: kernel-adaptation-n950
Repos:
    - mer-core-armv7hl
    - ce-adaptation-n9xx-common
    - ce-adaptation-n950-n9
    - ce-utils-armv7hl
    - ce-mw-shared-armv7hl
    - ce-ux-mtf-armv7hl
    - ce-apps-armv7hl
Groups:
    - Nokia N950 Support
    - Nokia N950 Proprietary Support
ExtraPackages:
    - usb-moded-config-n950-n9
    - mce
    - meego-handset-camera
PostScripts:
    # TODO: Because of https://bugs.meego.com/show_bug.cgi?id=20493#c1
    # we can't use the armv7nhl here
    - arch-armv7hl
    - meegotouch-n950
    # We don't have so much power with N900 than others so we need to wait a bit longer
    - mcompositor-app-wait-delay
