Name: MeeGo Tablet N900 Community Edition (Testing)
Platform: CETABLET
FileName: tablet-armv7nhl-n900-ce-testing
Part: n900-ce
Mic2Options: -f raw --save-kernel --arch=armv7nhl --record-pkgs=name
Architecture: armv7hl
Kernel: kernel-adaptation-n900
Active: False
Repos:
    - oss-1.2-daily
    - non-oss-1.2-daily
    - ce-testing
Groups:
    - Nokia N900 Support
    - Nokia N900 Proprietary Support
ExtraPackages:
    # Non-oss part of N900 camera for focus etc.
    - gst-nokia-camera
    # Adding n900 specific perf
    - perf-adaptation-n900
    - usb-moded-config-n900
PostScripts:
    # Because of https://bugs.meego.com/show_bug.cgi?id=20493#c1
    # we can't use the armv7nhl here
    - arch-armv7hl
    - fstab-n900
    - serial-n900
    - meegotouch-n900
    # Reduce the amount of memory given for GLESv2 apps
    - n900-powervr-ini
    - meego-ux-daemon-n900-homekey
