Name: MeeGo Handset N900 Community Edition (Testing)
Platform: CE-HANDSET-1.3
FileName: handset-armv7nhl-n900-ce-testing
Part: n900-ce
Mic2Options: -f raw --save-kernel --arch=armv7hl --record-pkgs=name
Architecture: armv7nhl
Kernel: kernel-adaptation-n900
Repos:
    - non-oss-trunk-testing-daily
Groups:
    - Nokia N900 Support
    - Nokia N900 Proprietary Support
ExtraPackages:
    # Non-oss part of N900 camera for focus etc.
    - gst-nokia-camera
    # Adding n900 specific perf
    # TODO: Disabled atm. because of gcc 4.6.0 compile problems.
    #- perf-adaptation-n900
    # CE related n900 specific config so isn't in Nokia N900 Support.
    - usb-moded-config-n900
    # Because of the SGX drivers we need setuid version of Xorg
    - xorg-x11-server-Xorg-setuid
PostScripts:
    # TODO: Because of https://bugs.meego.com/show_bug.cgi?id=20493#c1
    # we can't use the armv7nhl here
    - arch-armv7hl
    - fstab-n900
    - meegotouch-n900
    # Reduce the amount of memory given for GLESv2 apps
    - n900-powervr-ini
