Name: MeeGo Tablet N900 DE (Acceptance)
Platform: N900DE
FileName: tablet-armv7nhl-n900-de-acceptance
Groups:
    - MeeGo Tablet
    - MeeGo Tablet Applications
PostScripts:
    - n900-tablet-gconf
    - tablet-sensor-hack
    - meego-ux-daemon-n900-homekey
Repos:
    - oss
    - non-oss
    - de-testing
    - de-tablet-devel
ExtraPackages:
    # These apps are not in Tablet so we add them from handset
    - meego-handset-dialer
    - meego-handset-sms
    # Added to enable camera backend
    - gst-plugins-camera
    # meego-app-browser doesn't compile for ARM currently...
    - -meego-app-browser
    - -meego-app-browser-ffmpeg-oss
    # ... using fennec-qt instead
    - fennec-qt
    # Conflicts with contextkit-meego-battery-upower
    - -contextkit-maemo-battery-rx51-bin
