Name: MeeGo Tablet N900 CE (Testing)
Platform: CETABLET
FileName: tablet-armv7nhl-n900-ce-testing
Part: n900-ce
Mic2Options: -f raw --save-kernel --arch=armv7nhl --record-pkgs=name
Architecture: armv7nhl
Kernel: kernel-adaptation-n900
Repos:
    - ce-testing
Groups:
    - Nokia N900 Support
    - Nokia N900 Proprietary Support
PostScripts:
    - fstab-n900
    - serial-n900
    - meegotouch-n900
    - meego-ux-daemon-n900-homekey
