Name: Ewrt Handset N950
FileName: ewrt-handset-armv7hl-n950
Architecture: armv7hl
Inherit:
    - MER
    - EWRT-HANDSET
    - EWRT-ADAPTATION-N950-N9
ExtraPackages:
    - usb-moded-config-n950-n9
    # Wifi indicator needs this.
    #- contextkit-maemo-mce
PostScripts:
    # TODO: Because of https://bugs.meego.com/show_bug.cgi?id=20493#c1
    # we can't use the armv7nhl here
    - arch-armv7hl
    #- meegotouch-n950
    # We don't have so much power with N900 than others so we need to wait a bit longer
    #- mcompositor-app-wait-delay
