ExternalConfigs:
    - configs/Nemo/handset/

Default:
    Active: True
    Language: en_US.UTF-8
    Keyboard: us
    SaveRepos: True
    Timezone: America/Los_Angeles
    RootPass: meego
    DefaultUser: meego
    DefaultUserPass: meego
    PartSize: 1900
    Schedule: "*"
    Active: True
    PostScripts:
        - cleanup
        - nocursor
        - rpm
        - bootchart
        - handset-app-theme-fixes
        - plymouth-lite-ce
        - meegotouch-translations
        - prelink
    NoChrootScripts:
        - buildname

NEMO-HANDSET:
    Baseline: "Nemo"
    Groups:
        - Mer Core
        - Mer Graphics Common
        - Mer Connectivity
        - Mer Minimal Xorg
        - MTF Handset UX
        - Nemo Utils
        - Nemo Apps
    PostScripts:
        - uxlaunch-symlink-mtf
        # ohmd spam fix.
        - ohm-modules-ban
    ExtraPackages:
        - openssh-clients
        - openssh-server
        - xterm
