ExternalConfigs:
    - configs/Nemo/core/
    - configs/Nemo/handset/
    - configs/Nemo/tv/

Default:
    Active: True
    Baseline: "Nemo"
    Language: en_US.UTF-8
    Keyboard: us
    SaveRepos: True
    Timezone: America/Los_Angeles
    RootPass: meego
    DefaultUser: meego
    DefaultUserPass: meego
    PartSize: 1900
    Schedule: "*"
    Active: True
    PostScripts:
        - cleanup
        - rpm
        - prelink
    NoChrootScripts:
        - buildname

MER:
    Repos:
        - mer-core
    Groups:
        - Mer Core
        - Mer Graphics Common
        - Mer Connectivity

NEMO-HANDSET:
    Repos:
        - ce-utils
        - ce-mw-shared
        - ce-mw-mtf
        - ce-apps
        - ce-apps-mtf
        - ce-ux-mtf
        - ce-mtf-tracker-related-apps
    Groups:
        - Nemo Middleware Shared
        - Nemo Utils
        - Nemo Apps
        - Nemo Apps MTF
        - MTF Handset UX
        - MTF Tracker Related Apps
    PostScripts:
        - plymouth-lite-ce
        - nocursor
        - uxlaunch-symlink-mtf
    ExtraPackages:
        - openssh-clients
        - openssh-server
        - xterm
        - ce-backgrounds
        - plymouth-lite
        - vim-enhanced

NEMO-UX-XBMC:
    Repos:
        - ce-utils
        - ce-mw-shared
        - ce-ux-xbmc
        - ce-apps
    Group:
        - Nemo Utils
    ExtraPackages:
        - xbmc
        - openssh-clients
        - openssh-server
        - ce-backgrounds
        - plymouth-lite
        - vim-enhanced
    PostScripts:
        - uxlaunch-symlink-xbmc

NEMO-ADAPTATION-N900:
    Part: n900-ce
    Kernel: kernel-adaptation-n900
    Mic2Options: -f raw --save-kernel --record-pkgs=name --pkgmgr=yum
    Repos:
        - ce-adaptation-n9xx-common
        - ce-adaptation-n900
    Groups:
        - Nokia N900 Support
        - Nokia N900 Proprietary Support
    PostScripts:
        - fstab-n900
        # bq module causes instability, so removing for now.
        - n900-bq27x00_battery-removal

NEMO-ADAPTATION-N950-N9:
    PartSize: 3500
    FileSystem: ext3
    Kernel: kernel-adaptation-n950
    Mic2Options: -f fs --compress-disk-image=tar.bz2 --save-kernel --record-pkgs=name --pkgmgr=yum
    Repos:
        - ce-adaptation-n9xx-common
        - ce-adaptation-n950-n9
    Groups:
        - Nokia N950 Support
        - Nokia N950 Proprietary Support
    ExtraPackages:
        - policy-settings-basic-n950
        - mce
        - meego-handset-camera
        - xorg-x11-xauth

NEMO-ADAPTATION-x86-generic:
    PartSize: 3000
    FileSystem: ext3
    Bootloader: True
    BootloaderOptions: --menu="autoinst:Installation:systemd.unit=installer-shell.service"
    #BootloaderAppend: "quiet"
    BootloaderTimeout: 0
    StartX: True
    Kernel: kernel-adaptation-pc
    Mic2Options: -f liveusb --record-pkgs=name --pkgmgr=yum
    Repos:
        - ce-adaptation-x86-generic
    Groups:
        - Intel x86 Generic Support
        - Mer Minimal Xorg

NEMO-ADAPTATION-PANDABOARD:
    Part: pandaboard-sd
    Kernel: kernel-adaptation-pandaboard
    Mic2Options: -f raw --record-pkgs=name --pkgmgr=yum
    Repos:
        - ce-adaptation-pandaboard
    ExtraPackages:
        - xorg-x11-server-Xorg-setuid
        - pulseaudio-module-x11 
        - xorg-x11-xauth
        - pvr-omap4
        - pvr-omap4-kernel
        - pvr-omap4-libEGL
        - pvr-omap4-libGLESv1
        - pvr-omap4-libGLESv2
        - u-boot-omap4panda
        - x-loader-omap4panda
        - linux-firmware-ti-connectivity
