Repositories:
    -   Name: mer-core
        Url:  http://releases.merproject.org/releases/latest/builds/@ARCH@/packages/

    -   Name: ce-adaptation-x86-generic
        Url:  http://repo.pub.meego.com/CE:/Adaptation:/x86-generic/Mer_Core_@ARCH@/

    -   Name: ce-adaptation-n900
        Url:  http://repo.pub.meego.com/CE:/Adaptation:/N900/CE_Adaptation_N9xx-common_@ARCH@/

    -   Name: ce-adaptation-n9xx-common
        Url:  http://repo.pub.meego.com/CE:/Adaptation:/N9xx-common/Mer_Core_@ARCH@/

    -   Name: ce-adaptation-n950-n9
        Url:  http://repo.pub.meego.com/CE:/Adaptation:/N950-N9/CE_Adaptation_N9xx-common_@ARCH@/

    -   Name: ce-adaptation-pandaboard
        Url:  http://repo.pub.meego.com/home:/sage:/Mer:/Adaptation:/pandaboard/Mer_Core_@ARCH@/

    -   Name: ce-utils
        Url:  http://repo.pub.meego.com/CE:/Utils/Mer_Core_@ARCH@/

    -   Name: ce-mw-shared
        Url:  http://repo.pub.meego.com/CE:/MW:/Shared/Mer_Core_@ARCH@/

    -   Name: ce-mw-mtf
        Url:  http://repo.pub.meego.com/CE:/MW:/MTF/CE_MW_Shared_@ARCH@/

    -   Name: ce-ux-mtf
        Url:  http://repo.pub.meego.com/CE:/UX:/MTF/CE_MW_MTF_@ARCH@/

    -   Name: ce-mtf-tracker-related-apps
        Url:  http://repo.pub.meego.com/Project:/MTF:/Tracker/CE_UX_MTF_@ARCH@/

    -   Name: ce-apps
        Url:  http://repo.pub.meego.com/CE:/Apps/CE_MW_Shared_@ARCH@/

    -   Name: ce-apps-mtf
        Url:  http://repo.pub.meego.com/CE:/Apps:/MTF/CE_MW_MTF_@ARCH@/

    -   Name: ce-ux-xbmc
        Url:  http://repo.pub.meego.com/home:/sage:/xbmc/CE_Apps_@ARCH@/
