Repositories:
    -   Name: mer-core-i586
        Url:  http://monster.tspre.org/~merreleases/releases/0.20111020.1/builds/i586/packages/

    -   Name: mer-core-armv7hl
        Url:  http://monster.tspre.org/~merreleases/releases/0.20111020.1/builds/armv7hl/packages/

    -   Name: ce-adaptation-x86-generic
        Url:  http://repo.pub.meego.com/CE:/Adaptation:/x86-generic/Mer_Core_i586

    -   Name: ce-adaptation-n900
        Url:  http://repo.pub.meego.com/CE:/Adaptation:/N900/CE_Adaptation_N9xx-common_armv7hl/

    -   Name: ce-adaptation-n9xx-common
        Url:  http://repo.pub.meego.com/CE:/Adaptation:/N9xx-common/Mer_Core_armv7hl/

    -   Name: ce-adaptation-n950-n9
        Url:  http://repo.pub.meego.com/CE:/Adaptation:/N950-N9/CE_Adaptation_N9xx-common_armv7hl/

    -   Name: ce-utils-i586
        Url:  http://repo.pub.meego.com/CE:/Utils/Mer_Core_i586/

    -   Name: ce-utils-armv7hl
        Url:  http://repo.pub.meego.com/CE:/Utils/Mer_Core_armv7hl/

    -   Name: ce-mw-shared-i586
        Url:  http://repo.pub.meego.com/CE:/MW:/Shared/Mer_Core_i586/

    -   Name: ce-mw-shared-armv7hl
        Url:  http://repo.pub.meego.com/CE:/MW:/Shared/Mer_Core_armv7hl/

    -   Name: ce-ux-mtf-i586
        Url:  http://repo.pub.meego.com/CE:/UX:/MTF/CE_MW_Shared_i586/

    -   Name: ce-ux-mtf-armv7hl
        Url:  http://repo.pub.meego.com/CE:/UX:/MTF/CE_MW_Shared_armv7hl/

    -   Name: ce-apps-i586
        Url:  http://repo.pub.meego.com/CE:/Apps/CE_MW_Shared_i586/

    -   Name: ce-apps-armv7hl
        Url:  http://repo.pub.meego.com/CE:/Apps/CE_MW_Shared_armv7hl/

