Name: MeeGo Handset N950 Community Edition (Testing)
Platform: CEHANDSET
FileName: handset-armv7nhl-n950-ce-testing
PackageArgs: ignoremissing
PartSize: 3500
FileSystem: ext3
Mic2Options: -f fs --compress-disk-image=tar.bz2 --save-kernel --arch=armv7nhl --record-pkgs=name
Architecture: armv7nhl
Kernel: kernel-adaptation-n950
Active: False
Repos:
    - oss-1.2-daily-n950
    - devel-devices-n950
    - ce-testing-n950
Groups:
    - Nokia N950 Support
    - Nokia N950 Proprietary Support
PostScripts:
    # Because of https://bugs.meego.com/show_bug.cgi?id=20493#c1
    # we can't use the armv7nhl here
    - arch-armv7hl
    - serial-n950
    - meegotouch-n950
    - console-n950
    - n950-usb-moded-fix