Name: MeeGo Handset N900 Community Edition (Testing)
Platform: N900CEHANDSET
FileName: handset-armv7nhl-n900-ce-testing
Repos:
    - ce-testing
Groups:
    # Adding the MeeGo UX applications.
    - MeeGo Tablet Applications
ExtraPackages:
    # We need this so we can select between silent and general profiles
    - profiled
