Name: MeeGo Handset N900 With Tablet Apps
Platform: N900DEHANDSET
FileName: handset-armv7nhl-n900-tablet-apps
Groups:
    - MeeGo Tablet Applications
PostScripts:
    - n900-tablet-gconf
    - tablet-sensor-hack
Repos:
    - de-testing
    - de-tablet-devel
ExtraPackages:
    # Add separate volume app so we have at least some volume control in the images.
    - meegovolume
    - orientation-contextkit-sensor
    # Adding the MeeGo ux theme
    - meego-ux-theme
RemovePackages:
    # The meego-app-browser doesn't compile for ARM currently so disabling it
    - meego-app-browser
    - meego-app-browser-ffmpeg-oss
