Name: MeeGo Handset N900 Community Edition (Testing)
Platform: CEHANDSET
FileName: handset-armv7nhl-n900-ce-testing
Part: n900-ce
Mic2Options: -f raw --save-kernel --arch=armv7nhl --record-pkgs=name
Architecture: armv7nhl
Kernel: kernel-adaptation-n900
Repos:
    - ce-testing
Groups:
    - Nokia N900 Support
    - Nokia N900 Proprietary Support
    # Adding the MeeGo UX applications.
    - MeeGo Tablet Applications
ExtraPackages:
    # Non-oss part of N900 camera for focus etc.
    - gst-nokia-camera
    # Because of following bugs we need to install the package manually:
    # https://bugs.meego.com/show_bug.cgi?id=19010
    # https://bugs.meego.com/show_bug.cgi?id=19011
    # https://bugs.meego.com/show_bug.cgi?id=19013
    - meego-ux-sharing-qml-ui
    # Orientation with MeeGo UX apps do not work without this
    - orientation-contextkit-sensor
    # Workaround for https://bugs.meego.com/show_bug.cgi?id=16394
    # Copy the .desktop files from this to the right places as temp solution.
    - meego-ux-appgrid
PostScripts:
    - fstab-n900
    - serial-n900
    - meegotouch-n900
    # Workaround for https://bugs.meego.com/show_bug.cgi?id=15039
    - tablet-sensor-hack
    # Rest of the workaround for dependencies of https://bugs.meego.com/show_bug.cgi?id=16394
    - meego-ux-desktop-file-fix
