Name: MeeGo Handset N900 CE with Tablet Apps
Platform: N900CEHANDSET
FileName: handset-armv7nhl-n900-ce-tablet-apps
Groups:
    - MeeGo Tablet Applications
PostScripts:
    - tablet-sensor-hack
Repos:
    - ce-testing
    - ce-tablet-devel
ExtraPackages:
    # Add separate volume app so we have at least some volume control in the images.
    - meegovolume
    - orientation-contextkit-sensor
