Name: MeeGo Handset N900 With Tablet Apps
Platform: N900DE
FileName: handset-armv7nhl-n900-tablet-apps
Groups:
    - X for Handsets
    - MeeGo Handset Desktop
    - MeeGo Handset Applications
    - MeeGo Tablet Applications
PostScripts:
    - n900-tablet-gconf
    - tablet-sensor-hack
Repos:
    - oss-trunk-daily
    - non-oss-trunk-daily
    - de-testing
    - de-tablet-devel
ExtraPackages:
    - orientation-contextkit-sensor
    # Tablet apps do not have proper dependencies to sharing-qml
    # https://bugs.meego.com/show_bug.cgi?id=15301
    - meego-ux-sharing-qml
    - -meego-app-browser
    - -meego-app-browser-ffmpeg-oss
