Name: MeeGo Handset N900 Developer Edition (Acceptance)
Platform: N900DE
FileName: handset-armv7nhl-n900-de-acceptance
Groups:
    - X for Handsets
    - MeeGo Handset Desktop
    - MeeGo Handset Applications
Repos:
    - oss-trunk-daily
    - non-oss-trunk-daily
    - de-testing
ExtraPackages:
    - meegovolume
