Name: MeeGo Handset N900 CE with Tablet Apps
Platform: N900CEHANDSET
FileName: handset-armv7nhl-n900-ce-tablet-apps
Groups:
    - MeeGo Tablet Applications
PostScripts:
    - tablet-sensor-hack
Repos:
    - ce-testing
    - ce-tablet-devel
ExtraPackages:
    - orientation-contextkit-sensor
