Name: MeeGo Handset N900 Community Edition (Testing)
Platform: N900CEHANDSET
FileName: handset-armv7nhl-n900-ce-testing
Repos:
    - ce-testing
Groups:
    # Adding the MeeGo UX applications.
    - MeeGo Tablet Applications
ExtraPackages:
    # We need this so we can select between silent and general profiles
    - profiled
    # Because of following bugs we need to install the package manually:
    # https://bugs.meego.com/show_bug.cgi?id=19010
    # https://bugs.meego.com/show_bug.cgi?id=19011
    # https://bugs.meego.com/show_bug.cgi?id=19013
    - meego-ux-sharing-qml-ui
