Name: MeeGo Handset N900 Community Edition (Testing)
Platform: N900CEHANDSET
FileName: handset-armv7nhl-n900-ce-testing
Repos:
    - ce-testing
Groups:
    # Adding the MeeGo UX applications.
    - MeeGo Tablet Applications
ExtraPackages:
    # Because of following bugs we need to install the package manually:
    # https://bugs.meego.com/show_bug.cgi?id=19010
    # https://bugs.meego.com/show_bug.cgi?id=19011
    # https://bugs.meego.com/show_bug.cgi?id=19013
    - meego-ux-sharing-qml-ui
    # Orientation with MeeGo UX apps do not work without this
    - orientation-contextkit-sensor
    # Workaround for https://bugs.meego.com/show_bug.cgi?id=16394
    # Copy the .desktop files from this to the right places as temp solution.
    - meego-ux-appgrid
PostScripts:
    # Workaround for https://bugs.meego.com/show_bug.cgi?id=15039
    - tablet-sensor-hack
    # Rest of the workaround for dependencies of https://bugs.meego.com/show_bug.cgi?id=16394
    - meego-ux-desktop-file-fix
