Name: MeeGo Handset N900 Developer Edition (Acceptance)
Platform: N900DEHANDSET
FileName: handset-armv7nhl-n900-de-acceptance
Repos:
    - de-testing
ExtraPackages:
    # Add volume control.
    - meego-volume-control
    # Adding usb-moded to the images, this will give us possibility to
    # choose between PC Suite mode and Mass storage mode.
    - usb-moded
RemovePackages:
    # Remove nokia-usb-networking because it conflicts with usb-moded
    - nokia-usb-networking
