Name: Mer Handset IA32 Community Edition (Testing)
Platform: MER-CE-HANDSET
FileName: mer-handset-ia32-ce-testing
PartSize: 3000
FileSystem: ext3
Bootloader: True
#BootloaderAppend: "quiet"
BootloaderTimeout: 0
BootloaderOptions: --menu="autoinst:Installation:systemd.unit=installer-shell.service"
StartX: True
Architecture: ia32
Mic2Options: -f livecd --arch=i586 --record-pkgs=name --pkgmgr=yum
Kernel: kernel-adaptation-pc
Repos:
    - mer-base-i586
    - mer-adaptation-x86
    - mer-utils-i586
    - mer-mw-shared-i586
    - mer-ux-mtf-i586
    - mer-ce-apps-i586
ExtraPackages:
    - acpid
    - linux-firmware
    - installer-shell
    - xorg-x11-drv-mtev
    - xorg-x11-drv-synaptics
    - xorg-x11-drv-intel
    - mesa-dri-i915-driver
    - mesa-dri-i965-driver

    - basesystem
    - mesa-libGLESv2
    - contextkit-meego-battery-upower
    - zypper
    - openssh-clients

    # Mer Base packages
    - bash
    - boardname
    - coreutils
    - crda
    - deltarpm
    - e2fsprogs
    - file
    - filesystem
    - iproute
    - iputils
    - kbd
    - lsb-release
    - mailcap
    - meego-release
    - net-tools
    - nss
    - pam
    - passwd
    - prelink
    - procps
    - readline
    - rootfiles
    - rpm
    - setup
    - shadow-utils
    - shared-mime-info
    - systemd-sysv
    - time
    - udev
    #- udisks
    #- upower
    - usbutils
    - util-linux
    - wireless-tools
    - wpa_supplicant
    - xdg-user-dirs
    - cjkuni-fonts
    - droid-sans-fonts
    - droid-sans-mono-fonts
    - droid-serif-fonts
    - fontpackages-filesystem
    - liberation-fonts-common
    - liberation-mono-fonts
    - liberation-sans-fonts
    - liberation-serif-fonts
    - uxlaunch
    - gzip
    - xorg-x11-server-Xorg
    - xorg-x11-drv-fbdev
    - xorg-x11-xauth
    - qt-qmlviewer
